<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlatilloSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id_restaurant'     => 1,
                'nombre'            =>'Michelada de tamarindo',
                'descripcion'       =>'Es muy bueno y quita el estres',
                'precio'            =>230,  
                'imagen'            =>'michelada.jpg',
                'categoria'         =>'bebida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Enchiladas',
                'descripcion'       =>'Ricas y delisiosas',
                'precio'            =>80,  
                'imagen'            =>'Enchiladas.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 3,
                'nombre'            =>'Tacos de suadero',
                'descripcion'       =>'Ricos y delisiosos',
                'precio'            =>50,  
                'imagen'            =>'Tacosdesuadero.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 3,
                'nombre'            =>'Chilaquiles',
                'descripcion'       =>'Ricos y delisiosos',
                'precio'            =>65,  
                'imagen'            =>'chilaquiles.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Huevos con jamon',
                'descripcion'       =>'De calidad para un desayuno rico',
                'precio'            =>40,  
                'imagen'            =>'Huevosconjamon.jpg',
                'categoria'         =>'desayuno',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Filete de pescado',
                'descripcion'       =>'De calidad',
                'precio'            =>140,  
                'imagen'            =>'filete.jpg',
                'categoria'         =>'comida',
                'status'            =>'no disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Huevos con tocino',
                'descripcion'       =>'De calidad para un desayuno rico',
                'precio'            =>45,  
                'imagen'            =>'Huevoscontocino.jpg',
                'categoria'         =>'desayuno',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Refresco coca cola 600 ml.',
                'descripcion'       =>'Para quitar la sed',
                'precio'            =>22,  
                'imagen'            =>'Cocacola.jpg',
                'categoria'         =>'bebida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 3,
                'nombre'            =>'Agua de tamarindo 600 ml.',
                'descripcion'       =>'Para quitar la sed',
                'precio'            =>20,  
                'imagen'            =>'Aguatamarindo.jpg',
                'categoria'         =>'bebida',
                'status'            =>'disponible',
            ],  
            [
                'id_restaurant'     => 1,
                'nombre'            =>'Agua de jamaica 600 ml.',
                'descripcion'       =>'Para quitar la sed',
                'precio'            =>20,  
                'imagen'            =>'aguadejamaica.jpg',
                'categoria'         =>'bebida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 1,
                'nombre'            =>'Agua de piña 600 ml',
                'descripcion'       =>'Para quitar la sed',
                'precio'            =>20,  
                'imagen'            =>'aguadepiña.jpg',
                'categoria'         =>'bebida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 1,
                'nombre'            =>'Corte de carne de res',
                'descripcion'       =>'Corte delisioso',
                'precio'            =>180,  
                'imagen'            =>'corte.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Alambre',
                'descripcion'       =>'Para disfrutar',
                'precio'            =>100,  
                'imagen'            =>'alambre.jpg',
                'categoria'         =>'Comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'HotKakes',
                'descripcion'       =>'Para disfrutar, ricos y delisiosos',
                'precio'            =>45,  
                'imagen'            =>'HotKakes.jpg',
                'categoria'         =>'desayuno',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Bonless',
                'descripcion'       =>'Para disfrutar',
                'precio'            =>100,  
                'imagen'            =>'Bonless.jpg',
                'categoria'         =>'Comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 3,
                'nombre'            =>'HotDog Especial',
                'descripcion'       =>'Contiene piña, quesillo y papas',
                'precio'            =>60,  
                'imagen'            =>'hotdogespecial.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 1,
                'nombre'            =>'Quesadilla de Adobada',
                'descripcion'       =>'Quesillo, carde adobada y cebolla',
                'precio'            =>50,  
                'imagen'            =>'quesadillaadobada.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Chocomilk',
                'descripcion'       =>'Licuado grande con leche o agua',
                'precio'            =>40,  
                'imagen'            =>'chocomilk.jpg',
                'categoria'         =>'bebida',
                'status'            =>'disponible',
            ],[
                'id_restaurant'     => 1,
                'nombre'            =>'Hamburguesa Sencilla',
                'descripcion'       =>'carne de res, tomate, cebolla y lechuga',
                'precio'            =>50,  
                'imagen'            =>'hamburguesasencilla.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Pastel de Zanahoria',
                'descripcion'       =>'porcion para 2 personas',
                'precio'            =>80,  
                'imagen'            =>'pastelzanahoria.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 3,
                'nombre'            =>'Capuchino de Vainilla',
                'descripcion'       =>'taza grande de sabor vainilla con leche',
                'precio'            =>60,  
                'imagen'            =>'capuchinovainilla.jpg',
                'categoria'         =>'bebida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 3,
                'nombre'            =>'Cerveza XX lager',
                'descripcion'       =>'frias',
                'precio'            =>30,  
                'imagen'            =>'xxlager.jpg',
                'categoria'         =>'bebida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Agua de Horchata',
                'descripcion'       =>'vaso de 1 litro',
                'precio'            =>40,  
                'imagen'            =>'horchata.jpg',
                'categoria'         =>'bebida',
                'status'            =>'no disponible',
            ],
            [
                'id_restaurant'     => 3,
                'nombre'            =>'Crepas de Cajeta',
                'descripcion'       =>'Contiene cajeta y lechera',
                'precio'            =>70,  
                'imagen'            =>'crepas.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 1,
                'nombre'            =>'Tacos de Azada',
                'descripcion'       =>'Contiene carne azada, cebolla y cilantro',
                'precio'            =>60,  
                'imagen'            =>'tacosazada.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Pizza de Peperoni',
                'descripcion'       =>'Peperoni, quezo mozarella y salsa de tomates',
                'precio'            =>200,  
                'imagen'            =>'peperoni.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Sandwich de pavo',
                'descripcion'       =>'Jamon de pavo, queso manchego y verduras',
                'precio'            =>80,  
                'imagen'            =>'sandwich.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 1,
                'nombre'            =>'Pollo a la piña',
                'descripcion'       =>'2 porciones de pollo con frijoles y verduras',
                'precio'            =>120,  
                'imagen'            =>'pollo.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 2,
                'nombre'            =>'Aguachile',
                'descripcion'       =>'con bastante limon ',
                'precio'            =>180,  
                'imagen'            =>'aguachile.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
            [
                'id_restaurant'     => 1,
                'nombre'            =>'Tarta de manzana',
                'descripcion'       =>'Porcion para 2 personas',
                'precio'            =>80,  
                'imagen'            =>'tartamanzana.jpg',
                'categoria'         =>'comida',
                'status'            =>'disponible',
            ],
        ];
        DB::table('platillos')->insert($data);
    }
}
